version: '3.8'

networks:
  prod_net:
    driver: bridge

services:
  simple-rag-backend:
    container_name: simple-rag-backend

    build:
      context: .

    volumes:
      - ./hf_home:/hf_home

    ports:
      - '8080:8080'

    networks:
      - prod_net

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]